name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set-up PHP

        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: install
        run: make install

      - name: tests
        run: make test

      - name: run linter
        run: make lint
