name: PHP CI

on:
  pull_request:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set-up PHP

        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: install
        run: make install

      - name: PHPUnit
        run: make test

      - name: run linter
        run: make lint

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCOmmand: make test-coverage
          coverageLocations: ${{github.workplace}}/build/logs/clover.xml:clover
          debug: true

